export { supabase, getCurrentUser, getSession } from './supabase';
export type { Database } from './database.types';
export {
  alertBackupForReceiverCheckIn,
  createBackupContact,
  createReceiver,
  deleteBackupContact,
  deleteReceiver,
  getReceiver,
  getAdminMe,
  getOperationsCheckInDetail,
  getOperationsCheckInSummary,
  listBackupContacts,
  listReceivers,
  pauseReceiver,
  resolveReceiverCheckIn,
  resumeReceiver,
  syncAuthenticatedUser,
  tryReceiverCheckInLater,
  updateBackupContact,
  updateReceiver,
  type BackupContactSetupInput,
  type BackupContactUpdateInput,
  type BackendBackupContact,
  type BackendAdminMe,
  type BackendChannel,
  type BackendCheckInStatus,
  type BackendConsentStatus,
  type BackendOperationsRecentCheckIn,
  type BackendOperationsCheckInDetail,
  type BackendOperationsEscalationDetail,
  type BackendEscalationResult,
  type BackendOperationsSummary,
  type BackendReceiverDetail,
  type BackendReceiverSummary,
  type BackendRelationshipType,
  type BackendTechProfile,
  type CreatedReceiver,
  type ReceiverSetupInput,
  type ReceiverUpdateInput,
  type SyncedBackendUser,
} from './backendApi';
export {
  exportUserData,
  downloadUserData,
  deleteUserDataOnly,
  deleteUserAccount,
} from './userData';
export {
  isBiometricAvailable,
  isBiometricEnrolled,
  getBiometricType,
  getBiometricName,
  isBiometricEnabled,
  enableBiometric,
  disableBiometric,
  getBiometricUserId,
  authenticateWithBiometric,
  getBiometricStatus,
} from './biometric';
export type { BiometricType, BiometricStatus } from './biometric';
