export { supabase, getCurrentUser, getSession } from './supabase';
export type { Database } from './database.types';
export { BackendRequestError, isPaidAccessRequiredError, PAID_ACCESS_REQUIRED_MESSAGE } from './backendErrors';
export {
  alertBackupForReceiverCheckIn,
  createBackupContact,
  createReceiver,
  deleteAccount,
  deleteBackupContact,
  deleteReceiver,
  exportAccountData,
  getBillingStatus,
  getReceiver,
  getAdminMe,
  getOperationsCheckInDetail,
  getOperationsCheckInSummary,
  listAdminAbuseReports,
  listBackupContacts,
  listReceivers,
  markAdminAbuseReportActionTaken,
  markAdminAbuseReportSafe,
  pauseReceiver,
  registerDeviceToken,
  requestAccountStepUp,
  resolveReceiverCheckIn,
  resumeReceiver,
  syncAuthenticatedUser,
  tryReceiverCheckInLater,
  updateBackupContact,
  updateReceiver,
  verifyAccountStepUp,
  type BackupContactSetupInput,
  type BackupContactUpdateInput,
  type BackendBackupContact,
  type BackendAbuseReportStatus,
  type BackendAdminMe,
  type BackendAdminAbuseReport,
  type BackendBillingInterval,
  type BackendBillingStatus,
  type BackendBillingStore,
  type BackendChannel,
  type BackendCheckInStatus,
  type BackendConsentStatus,
  type BackendOperationsRecentCheckIn,
  type BackendOperationsCheckInDetail,
  type BackendOperationsEscalationDetail,
  type BackendEscalationResult,
  type BackendOperationsSummary,
  type BackendReceiverDetail,
  type BackendReceiverSummary,
  type BackendRelationshipType,
  type BackendSensitiveAction,
  type BackendSubscriptionStatus,
  type BackendSubscriptionTier,
  type BackendStepUpRequestResult,
  type BackendStepUpVerifyResult,
  type BackendTechProfile,
  type CreatedReceiver,
  type ReceiverSetupInput,
  type ReceiverUpdateInput,
  type SyncedBackendUser,
} from './backendApi';
export {
  exportUserData,
  downloadUserData,
  deleteUserAccount,
} from './userData';
export {
  isBiometricAvailable,
  isBiometricEnrolled,
  getBiometricType,
  getBiometricName,
  isBiometricEnabled,
  enableBiometric,
  disableBiometric,
  getBiometricUserId,
  authenticateWithBiometric,
  getBiometricStatus,
} from './biometric';
export type { BiometricType, BiometricStatus } from './biometric';
export {
  configureRevenueCat,
  purchaseRevenueCatPackage,
  restoreRevenueCatPurchases,
  revenueCatAvailability,
  type RevenueCatPurchaseInterval,
} from './revenueCat';
