export { supabase, getCurrentUser, getSession } from './supabase';
export type { Database } from './database.types';
export {
  createBackupContact,
  createReceiver,
  deleteBackupContact,
  deleteReceiver,
  getReceiver,
  listBackupContacts,
  listReceivers,
  pauseReceiver,
  resolveReceiverCheckIn,
  resumeReceiver,
  syncAuthenticatedUser,
  updateBackupContact,
  updateReceiver,
  type BackupContactSetupInput,
  type BackupContactUpdateInput,
  type BackendBackupContact,
  type BackendChannel,
  type BackendCheckInStatus,
  type BackendConsentStatus,
  type BackendReceiverDetail,
  type BackendReceiverSummary,
  type BackendRelationshipType,
  type BackendTechProfile,
  type CreatedReceiver,
  type ReceiverSetupInput,
  type ReceiverUpdateInput,
  type SyncedBackendUser,
} from './backendApi';
export {
  exportUserData,
  downloadUserData,
  deleteUserDataOnly,
  deleteUserAccount,
} from './userData';
export {
  isBiometricAvailable,
  isBiometricEnrolled,
  getBiometricType,
  getBiometricName,
  isBiometricEnabled,
  enableBiometric,
  disableBiometric,
  getBiometricUserId,
  authenticateWithBiometric,
  getBiometricStatus,
} from './biometric';
export type { BiometricType, BiometricStatus } from './biometric';
