-- CB-010 (per-language seed): every in-code message template key in the eight BRD launch languages
-- (en, ar, es, hi, ur, ml, ta, bn) for the two channels whose body the backend renders itself (SMS) or
-- will submit as a WhatsApp Content Template (WHATSAPP). Voice uses scriptKey audio, not this table.
--
-- Provenance: the English rows are byte-identical to IN_CODE_MESSAGE_TEMPLATES in
-- apps/backend/src/modules/channels/message-catalog.templates.ts (asserted by message-catalog.seed.spec.ts).
-- Every other language is a MACHINE TRANSLATION written by the engineering agent on 2026-09-06 and has NOT
-- been reviewed by a native speaker; approvedAt stays NULL until it has (docs/handoffs/message-copy-review.md).
-- BRD FR-LNG-02 forbids sending unreviewed copy to a real receiver; fake mode is the only consumer today.
--
-- Format (message-catalog.seed.spec.ts parses these lines, keep it):
--   one row per line: ('<templateKey>', '<lang>', $body$<body>$body$, ARRAY['<var>', ...]),
--   {{name}} = required variable, {{#name}}...{{/name}} = optional section, identical sets to the English row;
--   reply keywords YES / HELP / STOP / REPORT / DONE stay in Latin letters because receivers type them back;
--   a body rendered with every optional section present stays <= 320 characters.
--
-- Idempotent: ON CONFLICT on the natural key (templateKey, language, channel) leaves any existing row -
-- including one corrected after native review - untouched. active = true so the catalog prefers these rows
-- over the in-code copy; rows are never deleted by this migration.
INSERT INTO "channel_templates" ("templateKey", "language", "channel", "bodyText", "variables", "active", "updatedAt")
SELECT
  seed.template_key,
  seed.language,
  seed_channel.channel::"Channel",
  seed.body_text,
  seed.variables,
  true,
  now()
FROM (
  VALUES
    -- consent_request
    ('consent_request', 'en', $body$Hi {{receiverName}}, {{senderDisplayName}} asked Nearby to check in on you with a short daily message.{{#personalNote}} Their note: "{{personalNote}}"{{/personalNote}} Reply YES to agree. Reply STOP to stop, REPORT to report.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'ar', $body$مرحباً {{receiverName}}، بناءً على طلب {{senderDisplayName}} ستصلك من Nearby رسالة قصيرة كل يوم للاطمئنان عليك.{{#personalNote}} ملاحظة من {{senderDisplayName}}: "{{personalNote}}"{{/personalNote}} أرسل YES للموافقة. أرسل STOP للإيقاف أو REPORT للإبلاغ.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'es', $body$Hola {{receiverName}}, {{senderDisplayName}} ha pedido a Nearby que le enviemos un breve mensaje cada día para saber cómo está.{{#personalNote}} Su nota: "{{personalNote}}"{{/personalNote}} Responda YES para aceptar. Responda STOP para detener o REPORT para reportar.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'hi', $body$नमस्ते {{receiverName}}, {{senderDisplayName}} ने Nearby से कहा है कि हम हर दिन एक छोटे संदेश से आपकी खैरियत पूछें।{{#personalNote}} उनका संदेश: "{{personalNote}}"{{/personalNote}} सहमति के लिए YES लिखकर जवाब दें। रोकने के लिए STOP, शिकायत के लिए REPORT लिखें।$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'ur', $body$محترم {{receiverName}}، {{senderDisplayName}} نے Nearby سے کہا ہے کہ ہم ہر روز ایک مختصر پیغام کے ذریعے آپ کی خیریت دریافت کریں۔{{#personalNote}} ان کا پیغام: "{{personalNote}}"{{/personalNote}} رضامندی کے لیے YES لکھ کر جواب دیں۔ روکنے کے لیے STOP، شکایت کے لیے REPORT لکھیں۔$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'ml', $body$നമസ്കാരം {{receiverName}}, ദിവസവും ഒരു ചെറിയ സന്ദേശത്തിലൂടെ താങ്കളുടെ സുഖവിവരം അന്വേഷിക്കാൻ {{senderDisplayName}} Nearby-യോട് ആവശ്യപ്പെട്ടിട്ടുണ്ട്.{{#personalNote}} അവരുടെ കുറിപ്പ്: "{{personalNote}}"{{/personalNote}} സമ്മതമാണെങ്കിൽ YES എന്ന് മറുപടി നൽകുക. നിർത്താൻ STOP, പരാതിപ്പെടാൻ REPORT എന്ന് അയയ്ക്കുക.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'ta', $body$வணக்கம் {{receiverName}}, தினமும் ஒரு சிறிய செய்தி மூலம் உங்கள் நலம் விசாரிக்க {{senderDisplayName}} Nearby-யிடம் கேட்டுள்ளார்.{{#personalNote}} அவரின் குறிப்பு: "{{personalNote}}"{{/personalNote}} சம்மதம் என்றால் YES என்று பதிலளிக்கவும். நிறுத்த STOP, புகார் அளிக்க REPORT என்று அனுப்பவும்.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('consent_request', 'bn', $body$প্রিয় {{receiverName}}, {{senderDisplayName}} Nearby-কে অনুরোধ করেছেন যে আমরা প্রতিদিন একটি ছোট বার্তায় আপনার খবর নিই।{{#personalNote}} তাঁর বার্তা: "{{personalNote}}"{{/personalNote}} সম্মতি দিতে YES লিখে উত্তর দিন। বন্ধ করতে STOP, অভিযোগ জানাতে REPORT লিখুন।$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),

    -- checkin_daily
    ('checkin_daily', 'en', $body$Hi {{receiverName}}, {{senderDisplayName}} is checking in on you today.{{#personalNote}} Their note: "{{personalNote}}"{{/personalNote}} Reply YES if you're okay or HELP if you need help. Reply STOP to stop, REPORT to report.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'ar', $body$مرحباً {{receiverName}}، هذه رسالة من {{senderDisplayName}} للاطمئنان عليك اليوم.{{#personalNote}} ملاحظة من {{senderDisplayName}}: "{{personalNote}}"{{/personalNote}} أرسل YES إذا كنت بخير أو HELP إذا كنت بحاجة إلى مساعدة. أرسل STOP للإيقاف أو REPORT للإبلاغ.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'es', $body$Hola {{receiverName}}, {{senderDisplayName}} quiere saber cómo está usted hoy.{{#personalNote}} Su nota: "{{personalNote}}"{{/personalNote}} Responda YES si está bien o HELP si necesita ayuda. Responda STOP para detener o REPORT para reportar.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'hi', $body$नमस्ते {{receiverName}}, {{senderDisplayName}} आज आपकी खैरियत जानना चाहते हैं।{{#personalNote}} उनका संदेश: "{{personalNote}}"{{/personalNote}} अगर आप ठीक हैं तो YES लिखें, मदद चाहिए तो HELP लिखें। रोकने के लिए STOP, शिकायत के लिए REPORT लिखें।$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'ur', $body$محترم {{receiverName}}، {{senderDisplayName}} آج آپ کی خیریت جاننا چاہتے ہیں۔{{#personalNote}} ان کا پیغام: "{{personalNote}}"{{/personalNote}} اگر آپ ٹھیک ہیں تو YES لکھیں، مدد درکار ہو تو HELP لکھیں۔ روکنے کے لیے STOP، شکایت کے لیے REPORT لکھیں۔$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'ml', $body$നമസ്കാരം {{receiverName}}, {{senderDisplayName}} ഇന്ന് താങ്കളുടെ സുഖവിവരം അന്വേഷിക്കുന്നു.{{#personalNote}} അവരുടെ കുറിപ്പ്: "{{personalNote}}"{{/personalNote}} സുഖമാണെങ്കിൽ YES എന്നും സഹായം വേണമെങ്കിൽ HELP എന്നും മറുപടി നൽകുക. നിർത്താൻ STOP, പരാതിപ്പെടാൻ REPORT എന്ന് അയയ്ക്കുക.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'ta', $body$வணக்கம் {{receiverName}}, {{senderDisplayName}} இன்று உங்கள் நலம் விசாரிக்கிறார்.{{#personalNote}} அவரின் குறிப்பு: "{{personalNote}}"{{/personalNote}} நலமாக இருந்தால் YES என்றும், உதவி தேவைப்பட்டால் HELP என்றும் பதிலளிக்கவும். நிறுத்த STOP, புகார் அளிக்க REPORT என்று அனுப்பவும்.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_daily', 'bn', $body$প্রিয় {{receiverName}}, {{senderDisplayName}} আজ আপনার খবর নিতে চান।{{#personalNote}} তাঁর বার্তা: "{{personalNote}}"{{/personalNote}} ভালো থাকলে YES লিখুন, সাহায্য লাগলে HELP লিখুন। বন্ধ করতে STOP, অভিযোগ জানাতে REPORT লিখুন।$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),

    -- checkin_retry
    ('checkin_retry', 'en', $body$Hi {{receiverName}}, we have not heard back from you yet. {{senderDisplayName}} is checking in on you.{{#personalNote}} Their note: "{{personalNote}}"{{/personalNote}} Reply YES if you're okay or HELP if you need help. Reply STOP to stop, REPORT to report.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'ar', $body$مرحباً {{receiverName}}، لم يصلنا ردك بعد. هذه رسالة من {{senderDisplayName}} للاطمئنان عليك.{{#personalNote}} ملاحظة من {{senderDisplayName}}: "{{personalNote}}"{{/personalNote}} أرسل YES إذا كنت بخير أو HELP إذا كنت بحاجة إلى مساعدة. أرسل STOP للإيقاف أو REPORT للإبلاغ.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'es', $body$Hola {{receiverName}}, aún no hemos recibido su respuesta. {{senderDisplayName}} quiere saber cómo está usted.{{#personalNote}} Su nota: "{{personalNote}}"{{/personalNote}} Responda YES si está bien o HELP si necesita ayuda. Responda STOP para detener o REPORT para reportar.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'hi', $body$नमस्ते {{receiverName}}, हमें अभी तक आपका जवाब नहीं मिला है। {{senderDisplayName}} आपकी खैरियत जानना चाहते हैं।{{#personalNote}} उनका संदेश: "{{personalNote}}"{{/personalNote}} अगर आप ठीक हैं तो YES लिखें, मदद चाहिए तो HELP लिखें। रोकने के लिए STOP, शिकायत के लिए REPORT लिखें।$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'ur', $body$محترم {{receiverName}}، ہمیں ابھی تک آپ کا جواب نہیں ملا۔ {{senderDisplayName}} آپ کی خیریت جاننا چاہتے ہیں۔{{#personalNote}} ان کا پیغام: "{{personalNote}}"{{/personalNote}} اگر آپ ٹھیک ہیں تو YES لکھیں، مدد درکار ہو تو HELP لکھیں۔ روکنے کے لیے STOP، شکایت کے لیے REPORT لکھیں۔$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'ml', $body$നമസ്കാരം {{receiverName}}, താങ്കളുടെ മറുപടി ഇതുവരെ ലഭിച്ചിട്ടില്ല. {{senderDisplayName}} താങ്കളുടെ സുഖവിവരം അന്വേഷിക്കുന്നു.{{#personalNote}} അവരുടെ കുറിപ്പ്: "{{personalNote}}"{{/personalNote}} സുഖമാണെങ്കിൽ YES എന്നും സഹായം വേണമെങ്കിൽ HELP എന്നും മറുപടി നൽകുക. നിർത്താൻ STOP, പരാതിപ്പെടാൻ REPORT എന്ന് അയയ്ക്കുക.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'ta', $body$வணக்கம் {{receiverName}}, உங்கள் பதில் இன்னும் எங்களுக்கு வரவில்லை. {{senderDisplayName}} உங்கள் நலம் விசாரிக்கிறார்.{{#personalNote}} அவரின் குறிப்பு: "{{personalNote}}"{{/personalNote}} நலமாக இருந்தால் YES என்றும், உதவி தேவைப்பட்டால் HELP என்றும் பதிலளிக்கவும். நிறுத்த STOP, புகார் அளிக்க REPORT என்று அனுப்பவும்.$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),
    ('checkin_retry', 'bn', $body$প্রিয় {{receiverName}}, আপনার উত্তর এখনও আমরা পাইনি। {{senderDisplayName}} আপনার খবর নিতে চান।{{#personalNote}} তাঁর বার্তা: "{{personalNote}}"{{/personalNote}} ভালো থাকলে YES লিখুন, সাহায্য লাগলে HELP লিখুন। বন্ধ করতে STOP, অভিযোগ জানাতে REPORT লিখুন।$body$, ARRAY['personalNote', 'receiverName', 'senderDisplayName']),

    -- receiver_checkins_paused
    ('receiver_checkins_paused', 'en', $body$Hi {{receiverName}}, {{senderDisplayName}} has paused your Nearby check-ins. You will not get check-in messages until they are resumed. Reply STOP to stop, REPORT to report.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'ar', $body$مرحباً {{receiverName}}، تم إيقاف رسائل الاطمئنان من Nearby مؤقتاً بطلب من {{senderDisplayName}}. لن تصلك رسائل اطمئنان حتى يتم استئنافها. أرسل STOP للإيقاف أو REPORT للإبلاغ.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'es', $body$Hola {{receiverName}}, {{senderDisplayName}} ha pausado sus mensajes de Nearby. No recibirá mensajes hasta que se reanuden. Responda STOP para detener o REPORT para reportar.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'hi', $body$नमस्ते {{receiverName}}, {{senderDisplayName}} ने आपके Nearby संदेश कुछ समय के लिए रोक दिए हैं। दोबारा शुरू होने तक आपको संदेश नहीं मिलेंगे। रोकने के लिए STOP, शिकायत के लिए REPORT लिखें।$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'ur', $body$محترم {{receiverName}}، {{senderDisplayName}} نے آپ کے Nearby پیغامات کچھ وقت کے لیے روک دیے ہیں۔ دوبارہ شروع ہونے تک آپ کو پیغامات نہیں ملیں گے۔ روکنے کے لیے STOP، شکایت کے لیے REPORT لکھیں۔$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'ml', $body$നമസ്കാരം {{receiverName}}, {{senderDisplayName}} താങ്കളുടെ Nearby സന്ദേശങ്ങൾ താൽക്കാലികമായി നിർത്തിവച്ചിരിക്കുന്നു. പുനരാരംഭിക്കുന്നത് വരെ സന്ദേശങ്ങൾ ലഭിക്കില്ല. നിർത്താൻ STOP, പരാതിപ്പെടാൻ REPORT എന്ന് അയയ്ക്കുക.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'ta', $body$வணக்கம் {{receiverName}}, {{senderDisplayName}} உங்கள் Nearby செய்திகளை தற்காலிகமாக நிறுத்தியுள்ளார். மீண்டும் தொடங்கும் வரை செய்திகள் வராது. நிறுத்த STOP, புகார் அளிக்க REPORT என்று அனுப்பவும்.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_paused', 'bn', $body$প্রিয় {{receiverName}}, {{senderDisplayName}} আপনার Nearby বার্তাগুলি সাময়িকভাবে বন্ধ রেখেছেন। আবার শুরু না হওয়া পর্যন্ত আপনি বার্তা পাবেন না। বন্ধ করতে STOP, অভিযোগ জানাতে REPORT লিখুন।$body$, ARRAY['receiverName', 'senderDisplayName']),

    -- receiver_checkins_ended
    ('receiver_checkins_ended', 'en', $body$Hi {{receiverName}}, {{senderDisplayName}} has ended your Nearby check-ins. You will not get any more check-in messages. Reply REPORT to report.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'ar', $body$مرحباً {{receiverName}}، تم إنهاء رسائل الاطمئنان من Nearby بطلب من {{senderDisplayName}}. لن تصلك أي رسائل اطمئنان بعد الآن. أرسل REPORT للإبلاغ.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'es', $body$Hola {{receiverName}}, {{senderDisplayName}} ha finalizado sus mensajes de Nearby. No recibirá más mensajes. Responda REPORT para reportar.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'hi', $body$नमस्ते {{receiverName}}, {{senderDisplayName}} ने आपके Nearby संदेश बंद कर दिए हैं। अब आपको और संदेश नहीं मिलेंगे। शिकायत के लिए REPORT लिखें।$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'ur', $body$محترم {{receiverName}}، {{senderDisplayName}} نے آپ کے Nearby پیغامات ختم کر دیے ہیں۔ اب آپ کو مزید پیغامات نہیں ملیں گے۔ شکایت کے لیے REPORT لکھیں۔$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'ml', $body$നമസ്കാരം {{receiverName}}, {{senderDisplayName}} താങ്കളുടെ Nearby സന്ദേശങ്ങൾ അവസാനിപ്പിച്ചിരിക്കുന്നു. ഇനി സന്ദേശങ്ങൾ ലഭിക്കില്ല. പരാതിപ്പെടാൻ REPORT എന്ന് അയയ്ക്കുക.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'ta', $body$வணக்கம் {{receiverName}}, {{senderDisplayName}} உங்கள் Nearby செய்திகளை முடித்துவிட்டார். இனி செய்திகள் வராது. புகார் அளிக்க REPORT என்று அனுப்பவும்.$body$, ARRAY['receiverName', 'senderDisplayName']),
    ('receiver_checkins_ended', 'bn', $body$প্রিয় {{receiverName}}, {{senderDisplayName}} আপনার Nearby বার্তাগুলি বন্ধ করে দিয়েছেন। আপনি আর কোনো বার্তা পাবেন না। অভিযোগ জানাতে REPORT লিখুন।$body$, ARRAY['receiverName', 'senderDisplayName']),

    -- account_step_up_otp
    ('account_step_up_otp', 'en', $body$Your Nearby verification code is {{code}}. It is valid for {{validityMinutes}} minutes. Do not share this code with anyone.$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'ar', $body$رمز التحقق الخاص بك في Nearby هو {{code}}. صالح لمدة {{validityMinutes}} دقائق. لا تشارك هذا الرمز مع أي شخص.$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'es', $body$Su código de verificación de Nearby es {{code}}. Es válido durante {{validityMinutes}} minutos. No comparta este código con nadie.$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'hi', $body$आपका Nearby सत्यापन कोड {{code}} है। यह {{validityMinutes}} मिनट तक मान्य है। यह कोड किसी के साथ साझा न करें।$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'ur', $body$آپ کا Nearby تصدیقی کوڈ {{code}} ہے۔ یہ {{validityMinutes}} منٹ تک کارآمد ہے۔ یہ کوڈ کسی کے ساتھ شیئر نہ کریں۔$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'ml', $body$താങ്കളുടെ Nearby സ്ഥിരീകരണ കോഡ് {{code}} ആണ്. ഇത് {{validityMinutes}} മിനിറ്റ് സാധുവാണ്. ഈ കോഡ് ആരുമായും പങ്കുവയ്ക്കരുത്.$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'ta', $body$உங்கள் Nearby சரிபார்ப்புக் குறியீடு {{code}}. இது {{validityMinutes}} நிமிடங்களுக்கு செல்லுபடியாகும். இந்தக் குறியீட்டை யாருடனும் பகிர வேண்டாம்.$body$, ARRAY['code', 'validityMinutes']),
    ('account_step_up_otp', 'bn', $body$আপনার Nearby যাচাইকরণ কোড {{code}}। এটি {{validityMinutes}} মিনিট পর্যন্ত বৈধ। এই কোড কারও সাথে শেয়ার করবেন না।$body$, ARRAY['code', 'validityMinutes']),

    -- backup_contact_missed_checkin_alert
    ('backup_contact_missed_checkin_alert', 'en', $body$Hi {{contactName}}, this is Nearby. {{receiverName}} did not answer today's check-in from {{senderDisplayName}}.{{#channelsTried}} We tried {{channelsTried}}.{{/channelsTried}} Please check on them.{{#locationInstructions}} Where to find them: {{locationInstructions}}{{/locationInstructions}} Reply DONE once you have reached them.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'ar', $body$مرحباً {{contactName}}، هذه رسالة من Nearby. لم يصلنا رد من {{receiverName}} على رسالة الاطمئنان اليوم من {{senderDisplayName}}.{{#channelsTried}} حاولنا عبر {{channelsTried}}.{{/channelsTried}} نرجو الاطمئنان على {{receiverName}}.{{#locationInstructions}} كيفية الوصول: {{locationInstructions}}{{/locationInstructions}} أرسل DONE بعد التواصل.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'es', $body$Hola {{contactName}}, le escribe Nearby. {{receiverName}} no ha respondido hoy al mensaje de {{senderDisplayName}}.{{#channelsTried}} Lo intentamos por {{channelsTried}}.{{/channelsTried}} Por favor, compruebe que está bien.{{#locationInstructions}} Ubicación: {{locationInstructions}}{{/locationInstructions}} Responda DONE cuando haya hablado con {{receiverName}}.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'hi', $body$नमस्ते {{contactName}}, यह Nearby है। {{receiverName}} ने आज {{senderDisplayName}} के संदेश का जवाब नहीं दिया।{{#channelsTried}} हमने {{channelsTried}} से कोशिश की।{{/channelsTried}} कृपया उनकी खैरियत पूछें।{{#locationInstructions}} पता: {{locationInstructions}}{{/locationInstructions}} उनसे बात होने पर DONE लिखें।$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'ur', $body$محترم {{contactName}}، یہ Nearby ہے۔ {{receiverName}} نے آج {{senderDisplayName}} کے پیغام کا جواب نہیں دیا۔{{#channelsTried}} ہم نے {{channelsTried}} سے کوشش کی۔{{/channelsTried}} براہ کرم ان کی خیریت دریافت کریں۔{{#locationInstructions}} پتہ: {{locationInstructions}}{{/locationInstructions}} رابطہ ہو جانے پر DONE لکھیں۔$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'ml', $body$നമസ്കാരം {{contactName}}, ഇത് Nearby ആണ്. {{senderDisplayName}} അയച്ച ഇന്നത്തെ സന്ദേശത്തിന് {{receiverName}} മറുപടി നൽകിയില്ല.{{#channelsTried}} {{channelsTried}} വഴി ശ്രമിച്ചു.{{/channelsTried}} ദയവായി അവരെ അന്വേഷിക്കുക.{{#locationInstructions}} എവിടെ കാണാം: {{locationInstructions}}{{/locationInstructions}} അവരെ ബന്ധപ്പെട്ടാൽ DONE എന്ന് അയയ്ക്കുക.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'ta', $body$வணக்கம் {{contactName}}, இது Nearby. {{senderDisplayName}} அனுப்பிய இன்றைய செய்திக்கு {{receiverName}} பதிலளிக்கவில்லை.{{#channelsTried}} {{channelsTried}} மூலம் முயற்சித்தோம்.{{/channelsTried}} தயவுசெய்து அவரை விசாரிக்கவும்.{{#locationInstructions}} இருப்பிடம்: {{locationInstructions}}{{/locationInstructions}} அவரைத் தொடர்பு கொண்டபின் DONE என்று அனுப்பவும்.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_missed_checkin_alert', 'bn', $body$প্রিয় {{contactName}}, এটি Nearby। {{receiverName}} আজ {{senderDisplayName}}-এর বার্তার উত্তর দেননি।{{#channelsTried}} আমরা {{channelsTried}}-এর মাধ্যমে চেষ্টা করেছি।{{/channelsTried}} অনুগ্রহ করে তাঁর খবর নিন।{{#locationInstructions}} ঠিকানা: {{locationInstructions}}{{/locationInstructions}} যোগাযোগ হলে DONE লিখুন।$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),

    -- backup_contact_help_alert
    ('backup_contact_help_alert', 'en', $body$Hi {{contactName}}, this is Nearby. {{receiverName}} asked for help during a check-in from {{senderDisplayName}}.{{#channelsTried}} We reached them by {{channelsTried}}.{{/channelsTried}} Please contact them now.{{#locationInstructions}} Where to find them: {{locationInstructions}}{{/locationInstructions}} Reply DONE once you have reached them.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'ar', $body$مرحباً {{contactName}}، هذه رسالة من Nearby. وصلنا طلب مساعدة من {{receiverName}} أثناء رسالة اطمئنان من {{senderDisplayName}}.{{#channelsTried}} تواصلنا عبر {{channelsTried}}.{{/channelsTried}} نرجو التواصل مع {{receiverName}} الآن.{{#locationInstructions}} كيفية الوصول: {{locationInstructions}}{{/locationInstructions}} أرسل DONE بعد التواصل.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'es', $body$Hola {{contactName}}, le escribe Nearby. {{receiverName}} pidió ayuda durante el mensaje de {{senderDisplayName}}.{{#channelsTried}} Nos comunicamos por {{channelsTried}}.{{/channelsTried}} Por favor, póngase en contacto ahora.{{#locationInstructions}} Ubicación: {{locationInstructions}}{{/locationInstructions}} Responda DONE cuando haya hablado con {{receiverName}}.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'hi', $body$नमस्ते {{contactName}}, यह Nearby है। {{receiverName}} ने {{senderDisplayName}} के संदेश पर मदद मांगी है।{{#channelsTried}} हमने {{channelsTried}} से संपर्क किया।{{/channelsTried}} कृपया उनसे अभी संपर्क करें।{{#locationInstructions}} पता: {{locationInstructions}}{{/locationInstructions}} उनसे बात होने पर DONE लिखें।$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'ur', $body$محترم {{contactName}}، یہ Nearby ہے۔ {{receiverName}} نے {{senderDisplayName}} کے پیغام پر مدد مانگی ہے۔{{#channelsTried}} ہم نے {{channelsTried}} سے رابطہ کیا۔{{/channelsTried}} براہ کرم ان سے ابھی رابطہ کریں۔{{#locationInstructions}} پتہ: {{locationInstructions}}{{/locationInstructions}} رابطہ ہو جانے پر DONE لکھیں۔$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'ml', $body$നമസ്കാരം {{contactName}}, ഇത് Nearby ആണ്. {{senderDisplayName}} അയച്ച സന്ദേശത്തിന് {{receiverName}} സഹായം ചോദിച്ചു.{{#channelsTried}} {{channelsTried}} വഴി അവരെ ബന്ധപ്പെട്ടു.{{/channelsTried}} ദയവായി ഉടൻ അവരെ ബന്ധപ്പെടുക.{{#locationInstructions}} എവിടെ കാണാം: {{locationInstructions}}{{/locationInstructions}} അവരെ ബന്ധപ്പെട്ടാൽ DONE എന്ന് അയയ്ക്കുക.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'ta', $body$வணக்கம் {{contactName}}, இது Nearby. {{senderDisplayName}} அனுப்பிய செய்திக்கு {{receiverName}} உதவி கேட்டுள்ளார்.{{#channelsTried}} {{channelsTried}} மூலம் அவரைத் தொடர்பு கொண்டோம்.{{/channelsTried}} தயவுசெய்து உடனே அவரைத் தொடர்பு கொள்ளவும்.{{#locationInstructions}} இருப்பிடம்: {{locationInstructions}}{{/locationInstructions}} அவரைத் தொடர்பு கொண்டபின் DONE என்று அனுப்பவும்.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_help_alert', 'bn', $body$প্রিয় {{contactName}}, এটি Nearby। {{receiverName}} {{senderDisplayName}}-এর বার্তায় সাহায্য চেয়েছেন।{{#channelsTried}} আমরা {{channelsTried}}-এর মাধ্যমে যোগাযোগ করেছি।{{/channelsTried}} অনুগ্রহ করে এখনই তাঁর সাথে যোগাযোগ করুন।{{#locationInstructions}} ঠিকানা: {{locationInstructions}}{{/locationInstructions}} যোগাযোগ হলে DONE লিখুন।$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),

    -- backup_contact_sender_requested_alert
    ('backup_contact_sender_requested_alert', 'en', $body$Hi {{contactName}}, this is Nearby. {{senderDisplayName}} asked us to alert you about {{receiverName}} and would like you to check on them.{{#channelsTried}} We tried {{channelsTried}}.{{/channelsTried}}{{#locationInstructions}} Where to find them: {{locationInstructions}}{{/locationInstructions}} Reply DONE once you have reached them.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'ar', $body$مرحباً {{contactName}}، هذه رسالة من Nearby. بطلب من {{senderDisplayName}}، نرجو منك الاطمئنان على {{receiverName}}.{{#channelsTried}} حاولنا عبر {{channelsTried}}.{{/channelsTried}}{{#locationInstructions}} كيفية الوصول: {{locationInstructions}}{{/locationInstructions}} أرسل DONE بعد التواصل.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'es', $body$Hola {{contactName}}, le escribe Nearby. {{senderDisplayName}} nos pidió avisarle sobre {{receiverName}} y le pide que compruebe que está bien.{{#channelsTried}} Lo intentamos por {{channelsTried}}.{{/channelsTried}}{{#locationInstructions}} Ubicación: {{locationInstructions}}{{/locationInstructions}} Responda DONE cuando haya hablado con {{receiverName}}.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'hi', $body$नमस्ते {{contactName}}, यह Nearby है। {{senderDisplayName}} ने कहा है कि आपको {{receiverName}} के बारे में सूचित करें; कृपया उनकी खैरियत पूछें।{{#channelsTried}} हमने {{channelsTried}} से कोशिश की।{{/channelsTried}}{{#locationInstructions}} पता: {{locationInstructions}}{{/locationInstructions}} उनसे बात होने पर DONE लिखें।$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'ur', $body$محترم {{contactName}}، یہ Nearby ہے۔ {{senderDisplayName}} نے کہا ہے کہ آپ کو {{receiverName}} کے بارے میں آگاہ کریں؛ براہ کرم ان کی خیریت دریافت کریں۔{{#channelsTried}} ہم نے {{channelsTried}} سے کوشش کی۔{{/channelsTried}}{{#locationInstructions}} پتہ: {{locationInstructions}}{{/locationInstructions}} رابطہ ہو جانے پر DONE لکھیں۔$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'ml', $body$നമസ്കാരം {{contactName}}, ഇത് Nearby ആണ്. {{receiverName}}-നെ കുറിച്ച് താങ്കളെ അറിയിക്കാൻ {{senderDisplayName}} ആവശ്യപ്പെട്ടു; ദയവായി അവരെ അന്വേഷിക്കുക.{{#channelsTried}} {{channelsTried}} വഴി ശ്രമിച്ചു.{{/channelsTried}}{{#locationInstructions}} എവിടെ കാണാം: {{locationInstructions}}{{/locationInstructions}} അവരെ ബന്ധപ്പെട്ടാൽ DONE എന്ന് അയയ്ക്കുക.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'ta', $body$வணக்கம் {{contactName}}, இது Nearby. {{receiverName}} குறித்து உங்களுக்குத் தெரிவிக்க {{senderDisplayName}} கேட்டுள்ளார்; தயவுசெய்து அவரை விசாரிக்கவும்.{{#channelsTried}} {{channelsTried}} மூலம் முயற்சித்தோம்.{{/channelsTried}}{{#locationInstructions}} இருப்பிடம்: {{locationInstructions}}{{/locationInstructions}} அவரைத் தொடர்பு கொண்டபின் DONE என்று அனுப்பவும்.$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName']),
    ('backup_contact_sender_requested_alert', 'bn', $body$প্রিয় {{contactName}}, এটি Nearby। {{senderDisplayName}} বলেছেন {{receiverName}} সম্পর্কে আপনাকে জানাতে; অনুগ্রহ করে তাঁর খবর নিন।{{#channelsTried}} আমরা {{channelsTried}}-এর মাধ্যমে চেষ্টা করেছি।{{/channelsTried}}{{#locationInstructions}} ঠিকানা: {{locationInstructions}}{{/locationInstructions}} যোগাযোগ হলে DONE লিখুন।$body$, ARRAY['channelsTried', 'contactName', 'locationInstructions', 'receiverName', 'senderDisplayName'])
) AS seed(template_key, language, body_text, variables)
CROSS JOIN (VALUES ('SMS'), ('WHATSAPP')) AS seed_channel(channel)
ON CONFLICT ("templateKey", "language", "channel") DO NOTHING;
